# Generated by Django 5.1.3 on 2024-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Национальная кухня')),
                ('title', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('photo', models.ImageField(upload_to='media')),
                ('descriptions', models.CharField(max_length=150, verbose_name='Описание')),
                ('cooking', models.TextField(verbose_name='Как приготовить')),
                ('products', models.TextField(verbose_name='Ингредиенты')),
                ('dish', models.CharField(max_length=50, verbose_name='Тип блюда')),
                ('tableware', models.TextField(verbose_name='Тип приготовления')),
                ('time', models.CharField(max_length=50, verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
    ]
